param([Parameter(Mandatory=$true)][string]$SourceFolder,[ValidateSet('individual','combined')][string]$Mode='individual',[Parameter(Mandatory=$true)][string]$TemplatePath,[string]$FileName='',[string]$LocationPath='',[string]$GoogleMapsApiKey='')
$ErrorActionPreference='Stop';[Console]::OutputEncoding=[Text.Encoding]::UTF8
$source=[IO.Path]::GetFullPath($SourceFolder);$childClean=Join-Path $source '정제'
if((Split-Path $source -Leaf)-eq'정제'){$cleanFolder=$source;$baseFolder=Split-Path $source -Parent}
elseif(Test-Path -LiteralPath $childClean -PathType Container){$cleanFolder=$childClean;$baseFolder=$source}
else{$directFiles=@(Get-ChildItem -LiteralPath $source -File|Where-Object{$_.Extension-in'.xlsx','.xls'});if($directFiles.Count){$cleanFolder=$source;$baseFolder=Split-Path $source -Parent}else{throw '선택한 폴더 또는 하위 정제 폴더에 Excel 파일이 없습니다.'}}
$outputFolder=Join-Path $baseFolder '대시보드'
$files=@(Get-ChildItem -LiteralPath $cleanFolder -File | Where-Object {$_.Extension -in '.xlsx','.xls' -and $_.Name -notlike '~$*'})
if($FileName){$files=@($files|Where-Object{$_.Name-eq$FileName})}
if(!$files.Count){throw '정제 폴더에 Excel 파일이 없습니다.'};[IO.Directory]::CreateDirectory($outputFolder)|Out-Null
$template=[IO.File]::ReadAllText($TemplatePath,[Text.Encoding]::UTF8)
$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false
function Read-Dataset($file){$book=$excel.Workbooks.Open($file.FullName,0,$true);try{$sheet=$book.Worksheets.Item(1);$used=$sheet.UsedRange;$values=$used.Value2;$rows=$used.Rows.Count;$cols=$used.Columns.Count;$headerRow=0;for($r=1;$r-le[math]::Min(10,$rows)-and-not$headerRow;$r++){for($c=1;$c-le$cols;$c++){$h=([string]$values[$r,$c]-replace'\s+','');if($h-in@('학교','학교명')){$headerRow=$r;break}}};if(!$headerRow){$headerRow=if($rows-ge4){3}else{1}};$headers=@();for($c=1;$c-le$cols;$c++){$h=[string]$values[$headerRow,$c];if([string]::IsNullOrWhiteSpace($h)){$h="열$c"};$base=$h.Trim();$unique=$base;$suffix=2;while($headers-contains$unique){$unique="$base ($suffix)";$suffix++};$headers+=$unique};$items=@();for($r=$headerRow+1;$r-le$rows;$r++){$o=[ordered]@{};$has=$false;for($c=1;$c-le$cols;$c++){$v=$values[$r,$c];if($null-ne$v-and"$v"-ne''){$has=$true};$o[$headers[$c-1]]=$v};if($has){$items+=[pscustomobject]$o}};return [pscustomobject]@{name=[IO.Path]::GetFileNameWithoutExtension($file.Name);headers=$headers;rows=$items}}finally{$book.Close($false)}}
function Write-Dashboard($name,$datasets){$pack=[pscustomobject]@{datasets=@($datasets)};$json=$pack|ConvertTo-Json -Depth 8 -Compress;$locations=if($LocationPath-and(Test-Path -LiteralPath $LocationPath)){[IO.File]::ReadAllText($LocationPath,[Text.Encoding]::UTF8)}else{'[]'};$mapsKey=$GoogleMapsApiKey|ConvertTo-Json -Compress;$title="$name · 데이터 대시보드";$html=$template.Replace('__TITLE_TEXT__',$title.Replace('&','&amp;').Replace('<','&lt;')).Replace('__DATA_JSON__',$json.Replace('</','<\/')).Replace('__AI_ANALYSIS_JSON__','"OpenAI API 키가 설정되지 않아 규칙 기반 요약만 표시합니다."').Replace('__LOCATION_JSON__',$locations.Replace('</','<\/')).Replace('__GOOGLE_MAPS_API_KEY_JSON__',$mapsKey);$path=Join-Path $outputFolder ($name+'.html');[IO.File]::WriteAllText($path,$html,(New-Object Text.UTF8Encoding($false)));return $path}
try{$sets=@();foreach($file in $files){$sets+=Read-Dataset $file};$made=@();if($Mode-eq'individual'){foreach($set in $sets){$made+=Write-Dashboard $set.name @($set)}}else{$made+=Write-Dashboard '통합_대시보드' $sets};[pscustomobject]@{mode=$Mode;count=$made.Count;source=$cleanFolder;output=$outputFolder;files=@($made|ForEach-Object{[IO.Path]::GetFileName($_)})}|ConvertTo-Json -Depth 5 -Compress}finally{$excel.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null;[GC]::Collect();[GC]::WaitForPendingFinalizers()}
